### PR TITLE
2024.1

### PR DESCRIPTION
**Pull request by wwfranczyk**
This is a test build based on previously submitted changes.

### CODE REVIEW

**Comment by wwfranczyk** [comment]
Probably the best course of action would be:

- Merging #71 
- Merging #70 
- Closing this PR

**Comment by cdock1029** [comment]
@binaryfields Hello, maybe you can take a look?

**Comment by wwfranczyk** [comment]
Test build confirmed working stable on Arch (SteamOS).

**Comment by appelgriebsch** [comment]
@flathubbot build again

**Comment by appelgriebsch** [comment]
bot, build com.jetbrains.CLion

**Comment by appelgriebsch** [comment]
Hey, thanks for your PR. I've updated the repo today to the latest release 2024.1.4, considering all the pending changes on the build script. Please have a look. IMHO we could close this one now.

**Pull request closed without merging**
